-- ============================================================
-- FIX SCHEMA SQL cho Supabase
-- Dán toàn bộ file này vào Supabase SQL Editor rồi chạy (Run)
-- File này bổ sung các cột, bảng, constraint còn thiếu
-- so với code database-mysql.ts
-- ============================================================

-- ============================================================
-- 1. WISHLISTS: Thiếu UNIQUE constraint + cột updated_at
-- Code dùng: ON CONFLICT (user_id, product_id) DO NOTHING
-- Nếu thiếu UNIQUE → lỗi "no unique constraint matching"
-- ============================================================
DO $$
BEGIN
  -- Thêm cột updated_at nếu chưa có
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'wishlists' AND column_name = 'updated_at'
  ) THEN
    ALTER TABLE public.wishlists ADD COLUMN updated_at timestamptz DEFAULT now();
  END IF;
END $$;

-- Thêm UNIQUE constraint (user_id, product_id)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'wishlists_user_product_unique'
  ) THEN
    ALTER TABLE public.wishlists
      ADD CONSTRAINT wishlists_user_product_unique UNIQUE (user_id, product_id);
  END IF;
END $$;


-- ============================================================
-- 2. REVIEWS: Thiếu UNIQUE(user_id, product_id)
-- Code dùng: ON CONFLICT (user_id, product_id) DO UPDATE
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'reviews_user_product_unique'
  ) THEN
    ALTER TABLE public.reviews
      ADD CONSTRAINT reviews_user_product_unique UNIQUE (user_id, product_id);
  END IF;
END $$;


-- ============================================================
-- 3. BANNERS: Code dùng title, display_order, updated_at
-- nhưng schema chỉ có name, sort_order, không có updated_at
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'banners' AND column_name = 'title'
  ) THEN
    ALTER TABLE public.banners ADD COLUMN title varchar;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'banners' AND column_name = 'display_order'
  ) THEN
    ALTER TABLE public.banners ADD COLUMN display_order integer DEFAULT 0;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'banners' AND column_name = 'updated_at'
  ) THEN
    ALTER TABLE public.banners ADD COLUMN updated_at timestamptz DEFAULT now();
  END IF;
END $$;


-- ============================================================
-- 4. COUPONS: Code INSERT có cột "title" nhưng schema không có
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'coupons' AND column_name = 'title'
  ) THEN
    ALTER TABLE public.coupons ADD COLUMN title varchar;
  END IF;
END $$;


-- ============================================================
-- 5. APP_SETTINGS: Bảng không tồn tại trong schema
-- Code dùng: INSERT INTO app_settings (setting_key, setting_value, ...)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.app_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key varchar NOT NULL UNIQUE,
  setting_value text,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);


-- ============================================================
-- 6. PRODUCTS: Code dùng file_url, thumbnail nhưng cần đảm
-- bảo chúng tồn tại (schema đã có, chỉ double-check)
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'file_url'
  ) THEN
    ALTER TABLE public.products ADD COLUMN file_url varchar;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'thumbnail'
  ) THEN
    ALTER TABLE public.products ADD COLUMN thumbnail varchar;
  END IF;
END $$;


-- ============================================================
-- 7. USERS: Code dùng referral_code - đảm bảo tồn tại
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'referral_code'
  ) THEN
    ALTER TABLE public.users ADD COLUMN referral_code varchar;
  END IF;
END $$;


-- ============================================================
-- 8. DOWNLOADS: Code INSERT không dùng purchase_id, file_id
-- nhưng schema yêu cầu FK. Đảm bảo chúng nullable
-- ============================================================
-- Các cột này đã nullable trong schema, OK.


-- ============================================================
-- 9. NOTIFICATIONS: Code INSERT không dùng title, data, 
-- read_at, action_url. Đảm bảo chúng nullable
-- ============================================================
-- Các cột này đã nullable trong schema, OK.


-- ============================================================
-- 10. ADMIN_ACTIONS: Code INSERT có updated_at nhưng schema
-- đã có, chỉ cần đảm bảo deleted_at nullable
-- ============================================================
-- Đã OK trong schema.


-- ============================================================
-- 11. USER_PROFILES: Đảm bảo cột updated_at tồn tại
-- Code dùng: updated_at = NOW() trong INSERT
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'user_profiles' AND column_name = 'updated_at'
  ) THEN
    ALTER TABLE public.user_profiles ADD COLUMN updated_at timestamptz DEFAULT now();
  END IF;
END $$;


-- ============================================================
-- 12. PRODUCT_RATINGS: Đảm bảo có updated_at
-- Code INSERT: updated_at = NOW()
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'product_ratings' AND column_name = 'updated_at'
  ) THEN
    ALTER TABLE public.product_ratings ADD COLUMN updated_at timestamptz DEFAULT now();
  END IF;
END $$;


-- ============================================================
-- 13. PASSWORD_RESETS: Đảm bảo có created_at
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'password_resets' AND column_name = 'created_at'
  ) THEN
    ALTER TABLE public.password_resets ADD COLUMN created_at timestamptz DEFAULT now();
  END IF;
END $$;


-- ============================================================
-- 14. REVIEWS: Code INSERT có updated_at nhưng cần đảm bảo
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'reviews' AND column_name = 'updated_at'
  ) THEN
    ALTER TABLE public.reviews ADD COLUMN updated_at timestamptz DEFAULT now();
  END IF;
END $$;


-- ============================================================
-- 15. INDEX tối ưu hiệu năng cho các query thường dùng
-- ============================================================

-- Deposits: query theo user_id + status
CREATE INDEX IF NOT EXISTS idx_deposits_user_id ON public.deposits (user_id);
CREATE INDEX IF NOT EXISTS idx_deposits_status ON public.deposits (status);
CREATE INDEX IF NOT EXISTS idx_deposits_timestamp ON public.deposits (timestamp DESC);

-- Withdrawals: query theo user_id + status
CREATE INDEX IF NOT EXISTS idx_withdrawals_user_id ON public.withdrawals (user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_status ON public.withdrawals (status);
CREATE INDEX IF NOT EXISTS idx_withdrawals_created_at ON public.withdrawals (created_at DESC);

-- Purchases: query theo user_id + product_id
CREATE INDEX IF NOT EXISTS idx_purchases_user_id ON public.purchases (user_id);
CREATE INDEX IF NOT EXISTS idx_purchases_product_id ON public.purchases (product_id);
CREATE INDEX IF NOT EXISTS idx_purchases_created_at ON public.purchases (created_at DESC);

-- Products: query theo category + is_active
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products (category);
CREATE INDEX IF NOT EXISTS idx_products_is_active ON public.products (is_active);
CREATE INDEX IF NOT EXISTS idx_products_created_at ON public.products (created_at DESC);

-- Notifications: query theo user_id + is_read
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON public.notifications (is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications (created_at DESC);

-- Chats: query theo user_id + admin_id
CREATE INDEX IF NOT EXISTS idx_chats_user_id ON public.chats (user_id);
CREATE INDEX IF NOT EXISTS idx_chats_admin_id ON public.chats (admin_id);
CREATE INDEX IF NOT EXISTS idx_chats_created_at ON public.chats (created_at ASC);

-- Reviews: query theo product_id + user_id
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.reviews (product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON public.reviews (user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_created_at ON public.reviews (created_at DESC);

-- Wishlists: query theo user_id
CREATE INDEX IF NOT EXISTS idx_wishlists_user_id ON public.wishlists (user_id);

-- Coupons: query theo code + is_active
CREATE INDEX IF NOT EXISTS idx_coupons_code ON public.coupons (code);
CREATE INDEX IF NOT EXISTS idx_coupons_is_active ON public.coupons (is_active);

-- Downloads: query theo user_id + product_id
CREATE INDEX IF NOT EXISTS idx_downloads_user_id ON public.downloads (user_id);
CREATE INDEX IF NOT EXISTS idx_downloads_product_id ON public.downloads (product_id);
CREATE INDEX IF NOT EXISTS idx_downloads_downloaded_at ON public.downloads (downloaded_at DESC);

-- Referrals: query theo referrer_id
CREATE INDEX IF NOT EXISTS idx_referrals_referrer_id ON public.referrals (referrer_id);

-- Analytics Events: query theo event_type + created_at
CREATE INDEX IF NOT EXISTS idx_analytics_events_type ON public.analytics_events (event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_events_created_at ON public.analytics_events (created_at DESC);

-- Product Views: query theo product_id
CREATE INDEX IF NOT EXISTS idx_product_views_product_id ON public.product_views (product_id);

-- Admin Actions: query theo admin_id + created_at
CREATE INDEX IF NOT EXISTS idx_admin_actions_admin_id ON public.admin_actions (admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_actions_created_at ON public.admin_actions (created_at DESC);

-- User Coupons: query theo user_id + coupon_id
CREATE INDEX IF NOT EXISTS idx_user_coupons_user_id ON public.user_coupons (user_id);
CREATE INDEX IF NOT EXISTS idx_user_coupons_coupon_id ON public.user_coupons (coupon_id);

-- Login History: query theo user_id
CREATE INDEX IF NOT EXISTS idx_login_history_user_id ON public.login_history (user_id);
CREATE INDEX IF NOT EXISTS idx_login_history_created_at ON public.login_history (created_at DESC);

-- Users: query theo email, username, role
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users (role);
CREATE INDEX IF NOT EXISTS idx_users_status ON public.users (status);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON public.users (created_at DESC);


-- ============================================================
-- DONE! Kiểm tra kết quả:
-- ============================================================
SELECT 'Schema fix completed!' AS result,
       (SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public') AS total_tables,
       (SELECT count(*) FROM pg_indexes WHERE schemaname = 'public') AS total_indexes;
